{% set name = "libcufile" %}
{% set version = "1.18.1.6" %}
{% set cuda_version = "13.3" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set extension = "tar.xz" %}  # [not win]

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/{{ name }}/{{ platform }}/{{ name }}-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 5c67df2f09fb5538bf1687e0ad03bbda438f816808049ff4975547b91a6a71a6  # [linux64]
  sha256: 495f32e86abba34a3ab77bf6fe811569a30ec5b049d7167b516535f435b78cb2  # [aarch64]

build:
  number: 1
  skip: true  # [not (linux64 or aarch64)]

requirements:
  build:
    - cf-nvidia-tools 1.*  # [linux]
    - patchelf <0.18.0                      # [linux]

outputs:
  - name: libcufile
    build:
      binary_relocation: false
      missing_dso_whitelist:
        - "*/libcuda.so.*"
    files:
      - lib/libcufile*.so.*
      - targets/{{ target_name }}/lib/libcufile*.so.*
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - rdma-core                             # [linux]
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath-main.sh
      commands:
        # Note that the version of libcufile does not match
        # {{ version.split(".")[0] }} but the major version of libcufile_rdma does
        # match that. Also we must drop the last component of the version when
        # finding the versioned .so file.
        {% set full_version = version.split(".")[:-1] | join(".") %}
        - test -L $PREFIX/lib/libcufile.so.0
        - test -L $PREFIX/lib/libcufile_rdma.so.{{ version.split(".")[0] }}
        - test -L $PREFIX/lib/libcufile.so.{{ full_version }}
        - test -L $PREFIX/lib/libcufile_rdma.so.{{ full_version }}
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufile.so.0
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufile_rdma.so.{{ version.split(".")[0] }}
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufile.so.{{ full_version }}
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufile_rdma.so.{{ full_version }}
        - bash test-rpath-main.sh
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Library for NVIDIA GPUDirect Storage
      description: |
        The cuFile library provides a direct data path between GPU memory and storage.
      doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

  - name: libcufile-dev
    build:
      run_exports:
        - {{ pin_subpackage("libcufile", max_pin="x") }}
    files:
      - lib/libcufile*.so
      - lib/pkgconfig
      - targets/{{ target_name }}/include
      - targets/{{ target_name }}/lib/libcufile*.so
      - man/man3
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("libcufile", exact=True) }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - libcufile-static >={{ version }}
    test:
      commands:
        - test -L $PREFIX/lib/libcufile.so
        - test -L $PREFIX/lib/libcufile_rdma.so
        - test -f $PREFIX/targets/{{ target_name }}/include/cufile.h
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufile.so
        - test -L $PREFIX/targets/{{ target_name }}/lib/libcufile_rdma.so
        - test -d $PREFIX/man/man3
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Library for NVIDIA GPUDirect Storage
      description: |
        The cuFile library provides a direct data path between GPU memory and storage.
      doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

  - name: libcufile-static
    files:
      - targets/{{ target_name }}/lib/libcufile*_static.a
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufile_static.a
        - test -f $PREFIX/targets/{{ target_name }}/lib/libcufile_rdma_static.a
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Library for NVIDIA GPUDirect Storage
      description: |
        The cuFile library provides a direct data path between GPU memory and storage.
      doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

  - name: gds-tools
    build:
      missing_dso_whitelist:
        - "*/libcuda.so.*"
    files:
      - gds/tools
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - {{ stdlib("c") }}
      host:
        - cuda-version {{ cuda_version }}
        - libcufile-dev {{ version }}
        - libnuma  # [linux]
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("libcufile", max_pin="x") }}
        - {{ pin_compatible("libnuma", max_pin="x") }}  # [linux]
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - patchelf  # [linux]
      files:
        - test-rpath-gds.sh
      commands:
        - test -d $PREFIX/gds/tools
        - bash test-rpath-gds.sh
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_file: LICENSE
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: Library for NVIDIA GPUDirect Storage
      description: |
        The cuFile library provides a direct data path between GPU memory and storage.
      doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_file: LICENSE
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Library for NVIDIA GPUDirect Storage
  description: |
    The cuFile library provides a direct data path between GPU memory and storage.
  doc_url: https://docs.nvidia.com/gpudirect-storage/api-reference-guide/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
  feedstock-name: libcufile
